import Head from 'next/head'
import styles from 'src/styles/Home.module.css'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
import { useCallback, useEffect, useState } from 'react'

export default function Home() {

  const [count, setCount] = useState(0);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);

  const handleClick = useCallback(() => {
    if (count < 10){
      setCount(prevCount => prevCount + 1);
    }
  },[count]);

  const handleDisplay = useCallback(()=>{
    setIsShow(prevIsShow => !prevIsShow);
  },[])

  const handleChange = useCallback((e)=>{
    if (e.target.value.length > 5){
      alert("５文字以内にしてください。");
      return;
    }
    setText(e.target.value);
  },[]);

  useEffect(() => {
    document.body.style.backgroundColor = 'lightblue';
    return () => {
      document.body.style.backgroundColor = '';
    };
  },[count]);

return (
  <div className={styles.container}>
    {/* ReactにおいてはclassName属性でなければいけない */}
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <Header />
    {isShow ? <h1>{count}</h1> : null}
    <button onClick={handleClick}>ボタン</button>
    <button onClick={handleDisplay}>{isShow ? "カウント非表示" : "カウント表示"}</button>
    <input type='text' value={text} onChange={handleChange}/>
    <Main page="index"/>
    <Footer />
  </div>
  )
}
