import Head from 'next/head'
import styles from 'src/styles/Home.module.css'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
import { useEffect, useState } from 'react'

export default function Home() {

  const [count, setCount] = useState(0);

  const handleClick = () => {
    setCount(pre => pre + 1);
  };

  useEffect(() => {
    document.body.style.backgroundColor = 'lightblue';
    return () => {
      document.body.style.backgroundColor = '';
    };
  },[]);

return (
  <div className={styles.container}>
    {/* ReactにおいてはclassName属性でなければいけない */}
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <Header />
    <h1>{count}</h1>
    <button onClick={handleClick}>ボタン</button>
    <Main page="index"/>
    <Footer />
  </div>
  )
}
